apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: d59ea353-f0bf-4d50-9a71-4cd35dbeba22
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/d59ea353-f0bf-4d50-9a71-4cd35dbeba22/overlays/development
    repoURL: https://github.com/stephanie-cy/test-fla-gitops
    targetRevision: main
  destination:
    namespace: flacatusu
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
