apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d59ea353-f0bf-4d50-9a71-4cd35dbeba22-gitops
  description: This is GitOps manifest for d59ea353-f0bf-4d50-9a71-4cd35dbeba22   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d59ea353-f0bf-4d50-9a71-4cd35dbeba22
